language: node_js
node_js:
    - "6"
    - "7"
addons:
    code_climate:
        repo_token: e2384bf12b936d6abba64968856d48ff5224591a3ff90b68b2792336719e981f
after_script:
    - cat coverage/lcov.info | ./node_modules/.bin/codeclimate-test-reporter

